import 'package:flutter/material.dart';

import '../../core/backend/backend_client.dart';
import '../../core/theme/sh_theme.dart';
import '../journey/journey_runtime_service.dart';
import '../journey/journey_service.dart';
import 'lifecycle_models.dart';
import 'lifecycle_runtime_read_service.dart';
import 'lifecycle_runtime_request_service.dart';
import 'lifecycle_stage.dart';

class LifecycleAuthorityView extends StatefulWidget {
  const LifecycleAuthorityView({super.key, required this.stage, this.incomingItems = const []});
  final LifecycleStage stage;
  final List<JourneyLifecyclePayload> incomingItems;
  @override State<LifecycleAuthorityView> createState() => _LifecycleAuthorityViewState();
}
class _TargetDraft { _TargetDraft() : email = TextEditingController(); final TextEditingController email; final Set<String> selected = <String>{}; void dispose() => email.dispose(); }
class _LifecycleAuthorityViewState extends State<LifecycleAuthorityView> {
  final _read = const LifecycleRuntimeReadService(); final _request = const LifecycleRuntimeRequestService(); final _runtime = const JourneyRuntimeService(); final _journey = const JourneyService();
  final _targets = <_TargetDraft>[_TargetDraft()]; List<Map<String, dynamic>> _records = const []; List<JourneyLifecyclePayload> _journeyItems = const []; String? _currentAccountId; bool _busy = false;
  bool get _isClone => widget.stage.title == 'Clone'; bool get _isTransfer => widget.stage.title == 'Inheritance' || widget.stage.title == 'Succession'; bool get _hasJourneyChecklist => _isClone || _isTransfer;
  String get _requiredTransferPolicy => switch (widget.stage.title) {'Inheritance' => 'INHERITANCE', 'Succession' => 'SUCCESSION', _ => 'NON_TRANSFERABLE'};
  @override void initState() { super.initState(); _load(); }
  @override void dispose() { for (final t in _targets) t.dispose(); super.dispose(); }
  Future<String?> _resolveCurrentAccountId() async { final result = await backendClient.rpc('resolve_identity'); if (result is! List || result.isEmpty || result.first is! Map) return null; return (result.first as Map)['account_id']?.toString(); }
  Future<void> _load() async {
    try {
      late final List<Map<String, dynamic>> requestRows;
      switch (widget.stage.title) { case 'Clone': requestRows = await _read.listCloneAgreements(); break; case 'Inheritance': requestRows = await _read.listInheritanceAuthorizations(); break; case 'Succession': requestRows = await _read.listSuccessionRules(); break; default: requestRows = const <Map<String, dynamic>>[]; }
      final journeyRecords = await _journey.load(limit: 100); final accountId = await _resolveCurrentAccountId();
      final incoming = [for (final record in journeyRecords) if (record.eventId.isNotEmpty && record.eventType.isNotEmpty && (record.visibility == 'SHARED' || record.visibility == 'PUBLIC') && const {'MEMORY', 'KNOWLEDGE', 'LEARNING', 'EXPERIENCE'}.contains(record.eventType.toUpperCase())) JourneyLifecyclePayload(title: record.payload['title']?.toString().trim().isNotEmpty == true ? record.payload['title'].toString() : record.eventType, type: switch (record.eventType.toUpperCase()) {'EXPERIENCE' => 'Experience', 'KNOWLEDGE' || 'LEARNING' => 'Knowledge', 'MEMORY' => 'Memory', _ => record.eventType}, content: record.payload['content']?.toString() ?? '', isPrivate: false, date: record.occurredAt.toLocal().toString(), semanticSourceId: record.payload['memory_id']?.toString() ?? record.payload['knowledge_id']?.toString() ?? record.payload['experience_id']?.toString() ?? record.eventId, transferPolicy: record.transferPolicy)];
      if (mounted) setState(() { _records = requestRows; _journeyItems = incoming; _currentAccountId = accountId; });
    } catch (error) { if (mounted) _show(error); }
  }
  void _show(Object value) => ScaffoldMessenger.of(context).showSnackBar(value is SnackBar ? value : SnackBar(content: Text(value.toString())));
  void _addTarget() => setState(() => _targets.add(_TargetDraft()));
  void _removeTarget(int i) { if (_targets.length == 1) return; final t = _targets.removeAt(i); t.dispose(); setState(() {}); }
  void _toggle(int i, JourneyLifecyclePayload item) { final key = item.semanticSourceId ?? '${item.type}|${item.title}'; setState(() => _targets[i].selected.contains(key) ? _targets[i].selected.remove(key) : _targets[i].selected.add(key)); }
  Map<String, dynamic> _scope(_TargetDraft target) { final out = <String, List<String>>{}; for (final item in _journeyItems) { final key = item.semanticSourceId ?? '${item.type}|${item.title}'; if (!target.selected.contains(key)) continue; final name = switch (item.type.toLowerCase()) {'memory' => 'memory_ids', 'knowledge' => 'knowledge_ids', 'experience' => 'experience_ids', _ => 'journey_event_ids'}; (out[name] ??= <String>[]).add(key); } return out; }
  Future<void> _submit() async {
    if (_busy) return;
    for (final target in _targets) { final email = target.email.text.trim(); if (email.isEmpty || !email.contains('@')) { _show(FormatException('Enter a valid target email.')); return; } if (_isTransfer && target.selected.isEmpty) { _show(StateError('Select at least one shared Journey item.')); return; } }
    setState(() => _busy = true);
    try {
      for (final target in _targets) { final email = target.email.text.trim(); final scope = _scope(target); switch (widget.stage.title) { case 'Clone': await _request.createCloneAgreement(targetEmail: email); break; case 'Inheritance': await _request.createInheritanceAuthorization(targetEmail: email, scope: scope); break; case 'Succession': await _request.createSuccessionRule(targetEmail: email, scope: scope); break; } }
      for (final target in _targets) { target.email.clear(); target.selected.clear(); } await _load(); if (mounted) _show(SnackBar(content: Text('${widget.stage.title} request created.')));
    } catch (error) { if (mounted) _show(error); } finally { if (mounted) setState(() => _busy = false); }
  }
  bool _canExecute(Map<String, dynamic> record) { final status = record['status']?.toString().toUpperCase() ?? ''; if (_currentAccountId == null) return false; if (widget.stage.title == 'Inheritance') return status == 'APPROVED' && record['source_account_id']?.toString() == _currentAccountId; if (widget.stage.title == 'Succession') return status == 'ACTIVE' && record['successor_account_id']?.toString() == _currentAccountId; return widget.stage.title == 'Clone' && status == 'APPROVED'; }
  Future<void> _execute(Map<String, dynamic> record) async { final status = record['status']?.toString().toUpperCase() ?? ''; final id = (record['agreement_id'] ?? record['authorization_id'] ?? record['succession_id'])?.toString(); final allowedStatus = (_isClone || widget.stage.title == 'Inheritance') ? status == 'APPROVED' : status == 'ACTIVE'; if (id == null || id.isEmpty || !allowedStatus || !_canExecute(record)) return; final confirmed = await showDialog<bool>(context: context, builder: (context) => AlertDialog(title: Text('Execute ${widget.stage.title}?'), content: const Text('Execution is handled by the canonical runtime authority.'), actions: [TextButton(onPressed: () => Navigator.pop(context, false), child: const Text('Cancel')), FilledButton(onPressed: () => Navigator.pop(context, true), child: const Text('Execute'))])); if (confirmed != true || !mounted) return; setState(() => _busy = true); try { switch (widget.stage.title) { case 'Clone': await _runtime.createClone(agreementId: id, cloneName: 'Second Head Clone'); break; case 'Inheritance': await _runtime.recordInheritance(authorizationId: id); break; case 'Succession': await _runtime.executeSuccession(successionId: id); break; } await _load(); if (mounted) _show(SnackBar(content: Text('${widget.stage.title} completed.'))); } catch (error) { if (mounted) _show(error); } finally { if (mounted) setState(() => _busy = false); } }
  int _count(String type) => _journeyItems.where((item) => item.type.toLowerCase() == type.toLowerCase()).length;
  @override Widget build(BuildContext context) => Scaffold(appBar: AppBar(leading: const BackButton(), title: Text(widget.stage.title)), body: RefreshIndicator(onRefresh: _load, child: ListView(padding: const EdgeInsets.fromLTRB(18, 18, 18, 28), children: [_card(_hero()), const SizedBox(height: 18), _card(_target()), const SizedBox(height: 18), _card(_history())])));
  Widget _card(Widget child) => Container(padding: const EdgeInsets.all(18), decoration: BoxDecoration(color: shSurface.withValues(alpha: .72), borderRadius: BorderRadius.circular(24), border: Border.all(color: widget.stage.accent.withValues(alpha: .24))), child: child);
  Widget _hero() => Row(children: [_StageIcon(stage: widget.stage), const SizedBox(width: 18), Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(widget.stage.title, style: const TextStyle(fontSize: 26, fontWeight: FontWeight.w500, height: 1.1)), const SizedBox(height: 9), Text(widget.stage.subtitle, style: const TextStyle(fontSize: 13, color: shMuted, height: 1.45))]))]);
  Widget _target() => Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(_isClone ? 'Target & Journey' : 'Target & Incoming from Journey', style: const TextStyle(fontSize: 18, fontWeight: FontWeight.w500)), const SizedBox(height: 18), for (var i = 0; i < _targets.length; i++) ...[Text('Target ${i + 1}', style: const TextStyle(fontSize: 15, fontWeight: FontWeight.w500)), const SizedBox(height: 9), const Text('Email', style: TextStyle(fontSize: 12, color: shMuted)), const SizedBox(height: 6), TextField(controller: _targets[i].email, keyboardType: TextInputType.emailAddress, decoration: const InputDecoration(prefixIcon: Icon(Icons.mail_outline_rounded), hintText: 'Enter target email')), if (_hasJourneyChecklist) ...[const SizedBox(height: 15), Text(_isClone ? 'Shared Journey' : 'Shared Journey — selecting here activates ${_requiredTransferPolicy} for the selected item', style: const TextStyle(fontSize: 12, color: shMuted)), const SizedBox(height: 6), if (_journeyItems.isEmpty) const Text('No shared Journey data available.', style: TextStyle(fontSize: 13, color: shMuted)) else for (final item in _journeyItems) CheckboxListTile(contentPadding: EdgeInsets.zero, value: _isClone ? true : _targets[i].selected.contains(item.semanticSourceId ?? '${item.type}|${item.title}'), onChanged: _busy || _isClone ? null : (_) => _toggle(i, item), title: Text(item.title, style: const TextStyle(fontSize: 14)), subtitle: Text('${item.type} · ${item.date}', style: const TextStyle(fontSize: 11, color: shMuted)), controlAffinity: ListTileControlAffinity.leading)], if (!_isClone && _targets.length > 1) Align(alignment: Alignment.centerRight, child: TextButton.icon(onPressed: _busy ? null : () => _removeTarget(i), icon: const Icon(Icons.remove_circle_outline, size: 18), label: const Text('Remove target'))), if (i != _targets.length - 1) const SizedBox(height: 15)], if (!_isClone) ...[const SizedBox(height: 9), OutlinedButton.icon(onPressed: _busy ? null : _addTarget, icon: const Icon(Icons.add_rounded, size: 18), label: const Text('Add Target'))], const SizedBox(height: 15), Text(_isClone ? 'Target email is used for the clone authorization flow. Authorization is handled by Integrations.' : 'Select shared Journey data here. The Lifecycle stage applies its transfer policy when the request is submitted.', style: const TextStyle(fontSize: 13, color: shMuted, height: 1.4)), const SizedBox(height: 15), SizedBox(width: double.infinity, height: 48, child: FilledButton.icon(onPressed: _busy ? null : _submit, icon: Icon(_isClone ? Icons.copy_all_outlined : Icons.send_rounded, size: 18), label: Text(_busy ? 'Submitting…' : _isClone ? 'Create Clone' : 'Request ${widget.stage.title}', style: const TextStyle(fontSize: 14)))), const SizedBox(height: 18), _summaryRow()]);
  Widget _summaryRow() => Container(padding: const EdgeInsets.fromLTRB(18, 16, 18, 14), decoration: BoxDecoration(color: shBackground.withValues(alpha: .48), borderRadius: BorderRadius.circular(18), border: Border.all(color: shBorder)), child: Row(children: [_summary('Memory', _count('Memory')), _summary('Knowledge', _count('Knowledge')), _summary('Experience', _count('Experience'))]));
  Widget _summary(String label, int value) => Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text('$value', style: const TextStyle(fontSize: 20, fontWeight: FontWeight.w500)), const SizedBox(height: 3), Text(label, style: const TextStyle(fontSize: 12, color: shMuted))]));
  Widget _history() => Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(_isClone ? 'Clone Result' : 'Decision History', style: const TextStyle(fontSize: 18, fontWeight: FontWeight.w500)), const SizedBox(height: 18), if (_records.isEmpty) Text(_isClone ? 'No clone results yet.' : 'No decisions yet.', style: const TextStyle(color: shMuted, fontSize: 13)) else for (final r in _records) Card(child: ListTile(title: Text(r['status']?.toString() ?? 'UNKNOWN', style: const TextStyle(fontSize: 14)), subtitle: Text(r['created_at']?.toString() ?? '', style: const TextStyle(fontSize: 11, color: shMuted)), trailing: _canExecute(r) ? IconButton(icon: const Icon(Icons.play_arrow_rounded, size: 20), onPressed: _busy ? null : () => _execute(r)) : null))]);
}
class _StageIcon extends StatelessWidget { const _StageIcon({required this.stage}); final LifecycleStage stage; @override Widget build(BuildContext context) => Container(width: 76, height: 76, decoration: BoxDecoration(shape: BoxShape.circle, color: shBackground, border: Border.all(color: stage.accent.withValues(alpha: .42), width: 1.5), boxShadow: [BoxShadow(color: stage.accent.withValues(alpha: .13), blurRadius: 28, spreadRadius: 4)]), alignment: Alignment.center, child: Icon(stage.icon, size: 34, color: stage.accent)); }
