import { useCallback, useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Button, Pressable, ScrollView, Text, type ViewStyle } from 'react-native';
import { Redirect } from 'expo-router';
import { useAuth } from '../state/auth-context';
import { listExperiences, listKnowledge, listMemories, preserveSelectedTransferAsLegacy, type Experience, type Knowledge, type Memory, type TransferSelection } from '../features/inheritance/inheritance-service';
import { loadJourneyEvents, type JourneyEvent } from '../features/journey/journey-service';

export default function LegacyScreen() {
  const { session, context } = useAuth(); const currentShId = context?.shInstances[0]?.sh_id ?? ''; const currentAccountId = context?.account.account_id ?? '';
  const [events, setEvents] = useState<JourneyEvent[]>([]); const [memories, setMemories] = useState<Memory[]>([]); const [knowledge, setKnowledge] = useState<Knowledge[]>([]); const [experiences, setExperiences] = useState<Experience[]>([]);
  const [selectedJourneyIds, setSelectedJourneyIds] = useState<string[]>([]); const [selectedMemoryIds, setSelectedMemoryIds] = useState<string[]>([]); const [selectedKnowledgeIds, setSelectedKnowledgeIds] = useState<string[]>([]); const [selectedExperienceIds, setSelectedExperienceIds] = useState<string[]>([]);
  const [notice, setNotice] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false);
  const refresh = useCallback(async () => { if (!currentShId) return; setLoading(true); setError(null); try { const [journey, m, k, e] = await Promise.all([loadJourneyEvents(currentShId), listMemories(), listKnowledge(), listExperiences()]); setEvents(journey); setMemories(m.filter(v => v.sh_id === currentShId && ['CANDIDATE','ACTIVE','UPDATED'].includes(v.lifecycle))); setKnowledge(k.filter(v => v.sh_id === currentShId && ['CANDIDATE','ACTIVE'].includes(v.lifecycle))); setExperiences(e.filter(v => v.sh_id === currentShId && v.lifecycle === 'ACTIVE')); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load transfer scope'); } finally { setLoading(false); } }, [currentShId]);
  useEffect(() => { void refresh(); }, [refresh]); if (!session) return <Redirect href="/login" />; if (!context) return <ActivityIndicator />;
  const eligibleEvents = useMemo(() => events.filter(e => e.transfer_policy !== 'NON_TRANSFERABLE' && e.visibility !== 'PRIVATE' && e.transfer_policy !== 'PRIVATE'), [events]); const eligibleMemories = memories.filter(v => v.scope !== 'PRIVATE' && v.visibility !== 'OWNER_ONLY'); const eligibleKnowledge = knowledge.filter(v => v.scope !== 'PRIVATE' && v.visibility !== 'OWNER_ONLY'); const eligibleExperiences = experiences.filter(v => v.scope !== 'PRIVATE' && v.visibility !== 'OWNER_ONLY');
  const totalSelected = selectedJourneyIds.length + selectedMemoryIds.length + selectedKnowledgeIds.length + selectedExperienceIds.length; const toggle = (id: string, setter: React.Dispatch<React.SetStateAction<string[]>>) => setter(ids => ids.includes(id) ? ids.filter(v => v !== id) : [...ids, id]);
  async function preserve() { setBusy(true); setNotice(null); setError(null); try { const scope: TransferSelection = { memory_ids: selectedMemoryIds, knowledge_ids: selectedKnowledgeIds, experience_ids: selectedExperienceIds, journey_event_ids: selectedJourneyIds }; const v = await preserveSelectedTransferAsLegacy({ sourceShId: currentShId, scope }); setNotice(`Legacy preserved: ${String(v)}`); await refresh(); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to preserve Legacy'); } finally { setBusy(false); } }
  const card = (selected: boolean): ViewStyle => ({ borderWidth: 1, borderRadius: 10, padding: 12, borderColor: selected ? '#111827' : '#D1D5DB', backgroundColor: selected ? '#F3F4F6' : '#fff' });
  return <ScrollView contentContainerStyle={{ padding: 24, gap: 14 }}><Text style={{ fontSize: 28, fontWeight: '700' }}>Legacy</Text><Text>Legacy preserves selected eligible history. The current account and SH are informational.</Text><Text style={{ fontWeight: '600' }}>Current account</Text><Text>{currentAccountId}</Text><Text style={{ fontWeight: '600' }}>Current SH</Text><Text>{currentShId}</Text>{loading ? <ActivityIndicator /> : null}
    <ScopeList title="Memory records eligible for Legacy" items={eligibleMemories.map(v => ({ id: v.memory_id, title: 'MEMORY', content: v.content, meta: `Scope: ${v.scope} / Visibility: ${v.visibility}` }))} selected={selectedMemoryIds} onToggle={id => toggle(id, setSelectedMemoryIds)} card={card} /><ScopeList title="Knowledge records eligible for Legacy" items={eligibleKnowledge.map(v => ({ id: v.knowledge_id, title: 'KNOWLEDGE', content: v.content, meta: `Scope: ${v.scope} / Visibility: ${v.visibility}` }))} selected={selectedKnowledgeIds} onToggle={id => toggle(id, setSelectedKnowledgeIds)} card={card} /><ScopeList title="Experience records eligible for Legacy" items={eligibleExperiences.map(v => ({ id: v.experience_id, title: 'EXPERIENCE', content: v.content, meta: `Scope: ${v.scope} / Visibility: ${v.visibility}` }))} selected={selectedExperienceIds} onToggle={id => toggle(id, setSelectedExperienceIds)} card={card} /><ScopeList title="Journey records eligible for Legacy" items={eligibleEvents.map(v => ({ id: v.event_id, title: v.event_type, content: v.occurred_at, meta: `Policy: ${v.transfer_policy}` }))} selected={selectedJourneyIds} onToggle={id => toggle(id, setSelectedJourneyIds)} card={card} />
    <Button title={`Preserve selected history (${totalSelected})`} disabled={busy || totalSelected === 0} onPress={() => void preserve()} />{notice ? <Text>{notice}</Text> : null}{error ? <Text>{error}</Text> : null}</ScrollView>;
}
function ScopeList({ title, items, selected, onToggle, card }: { title: string; items: { id: string; title: string; content: string; meta: string }[]; selected: string[]; onToggle: (id: string) => void; card: (selected: boolean) => ViewStyle }) { return <><Text style={{ fontWeight: '600' }}>{title}</Text><Text>Only non-private, non-owner-only records are selectable.</Text>{items.length === 0 ? <Text>No eligible records are currently available.</Text> : null}{items.map(item => { const isSelected = selected.includes(item.id); return <Pressable key={item.id} onPress={() => onToggle(item.id)} style={card(isSelected)}><Text>{isSelected ? '☑' : '☐'} {item.title}</Text><Text>{item.content}</Text><Text>{item.meta}</Text></Pressable>; })}</>; }
