import { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Button, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { router } from 'expo-router';
import { SHShell } from '../components/sh-shell';
import { useAuth } from '../state/auth-context';
import { globalSearch, type GlobalSearchDomain, type GlobalSearchResult } from '../services/global-search';

const DOMAINS: Array<{ key: GlobalSearchDomain | 'ALL'; label: string }> = [{ key: 'ALL', label: 'All' }, { key: 'CONVERSATION', label: 'Conversation' }, { key: 'MEMORY', label: 'Memory' }, { key: 'KNOWLEDGE', label: 'Knowledge' }, { key: 'EXPERIENCE', label: 'Experience' }, { key: 'JOURNEY', label: 'Journey' }];
function snippet(result: GlobalSearchResult) {
  if (result.domain !== 'JOURNEY') return result.snippet;
  try { const parsed = JSON.parse(result.snippet) as Record<string, unknown>; for (const key of ['content','text','message','captured_text','representation','summary']) if (typeof parsed[key] === 'string' && parsed[key]) return parsed[key] as string; } catch {}
  return result.snippet;
}
export default function SearchScreen() {
  const { context } = useAuth();
  const shId = context?.sh_id ?? context?.shInstances.find(item => item.is_primary)?.sh_id ?? context?.shInstances[0]?.sh_id ?? null;
  const [query,setQuery]=useState(''); const [domain,setDomain]=useState<GlobalSearchDomain|'ALL'>('ALL'); const [results,setResults]=useState<GlobalSearchResult[]>([]); const [offset,setOffset]=useState(0); const [hasMore,setHasMore]=useState(false); const [loading,setLoading]=useState(false); const [error,setError]=useState<string|null>(null);
  const selectedDomains=useMemo(()=>domain==='ALL'?undefined:[domain],[domain]);
  async function runSearch(nextOffset=0){ if(!shId||!query.trim())return; setLoading(true);setError(null);try{const page=await globalSearch({shId,query,offset:nextOffset,limit:20,domains:selectedDomains});setResults(current=>nextOffset===0?page.results:[...current,...page.results]);setOffset(nextOffset);setHasMore(page.has_more);}catch(err){setError(err instanceof Error?err.message:'Global Search failed.');if(nextOffset===0)setResults([]);}finally{setLoading(false);}}
  useEffect(()=>{setResults([]);setOffset(0);setHasMore(false);},[domain]);
  return <SHShell title="Global Search" context={<><View style={{gap:6}}><Text style={{fontSize:13,fontWeight:'800',color:'#5D45A5'}}>D5 · BOUNDED SEARCH</Text><Text style={{fontSize:16,fontWeight:'700',color:'#22211F'}}>Authorized SH search</Text><Text style={{color:'#6B6A66'}}>Search runs through a bounded backend contract. Private Memory is never downloaded for client-side search.</Text></View></>}><ScrollView contentContainerStyle={styles.content}><Text style={styles.title}>Global SH Search</Text><Text style={styles.subtitle}>Conversation, Memory, Knowledge, Experience, and Journey within the authorized SH boundary.</Text><View style={styles.searchRow}><TextInput value={query} onChangeText={setQuery} onSubmitEditing={()=>void runSearch(0)} placeholder="Search SH…" placeholderTextColor="#777" style={styles.input} returnKeyType="search"/><Button title="Search" disabled={!query.trim()||loading} onPress={()=>void runSearch(0)}/></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.filters}>{DOMAINS.map(item=><Pressable key={item.key} onPress={()=>setDomain(item.key)} style={[styles.filter,domain===item.key&&styles.filterActive]}><Text style={domain===item.key?styles.filterActiveText:styles.filterText}>{item.label}</Text></Pressable>)}</ScrollView>{loading&&results.length===0?<View style={styles.center}><ActivityIndicator/><Text style={styles.muted}>Searching authorized context…</Text></View>:null}{error?<View style={styles.error}><Text style={styles.errorTitle}>Search unavailable</Text><Text style={styles.muted}>{error}</Text><Button title="Try again" onPress={()=>void runSearch(offset)}/></View>:null}{!loading&&!error&&query.trim()&&results.length===0?<View style={styles.empty}><Text style={styles.emptyTitle}>No authorized results</Text><Text style={styles.muted}>Tidak ada hasil pada domain dan SH scope yang dipilih.</Text></View>:null}<View style={{gap:10}}>{results.map(result=><View key={result.domain+':'+result.result_id} style={styles.result}><View style={styles.resultTop}><Text style={styles.domain}>{result.domain}</Text><Text style={styles.score}>{Math.round(result.relevance_score)} relevance</Text></View><Text style={styles.resultTitle}>{result.title}</Text><Text style={styles.snippet}>{snippet(result)}</Text><Text selectable style={styles.source}>Source: {result.source_ref??'bounded runtime source'}</Text><View style={styles.actions}><Button title="Chat" onPress={()=>router.push('/(tabs)/chat')}/><Button title="Journey" onPress={()=>router.push('/(tabs)/journey')}/></View></View>)}</View>{hasMore?<View style={styles.more}><Button title={loading?'Loading…':'Load more'} disabled={loading} onPress={()=>void runSearch(offset+20)}/></View>:null}</ScrollView></SHShell>;
}
const styles=StyleSheet.create({content:{padding:20,paddingBottom:36,gap:12},title:{fontSize:32,fontWeight:'800'},subtitle:{color:'#555',lineHeight:20},searchRow:{flexDirection:'row',alignItems:'center',gap:8},input:{flex:1,minHeight:48,borderWidth:1,borderColor:'#D5D2CB',borderRadius:12,paddingHorizontal:12,color:'#111',backgroundColor:'#FFF'},filters:{gap:8,paddingVertical:4},filter:{paddingHorizontal:12,paddingVertical:8,borderRadius:18,backgroundColor:'#E7E5E0'},filterActive:{backgroundColor:'#111'},filterText:{color:'#222'},filterActiveText:{color:'#FFF',fontWeight:'700'},result:{backgroundColor:'#FFF',borderRadius:14,padding:14,gap:7},resultTop:{flexDirection:'row',justifyContent:'space-between',gap:8},domain:{fontSize:12,fontWeight:'800',color:'#5D45A5'},score:{fontSize:11,color:'#777'},resultTitle:{fontSize:17,fontWeight:'700'},snippet:{color:'#222',lineHeight:20},source:{color:'#777',fontSize:11},actions:{flexDirection:'row',gap:8,marginTop:4},center:{paddingVertical:30,alignItems:'center',gap:8},muted:{color:'#666',lineHeight:19},error:{borderWidth:1,borderColor:'#E0B4A4',borderRadius:12,padding:12,gap:7},errorTitle:{color:'#9A3412',fontWeight:'800'},empty:{padding:18,borderRadius:12,backgroundColor:'#EEE',gap:6},emptyTitle:{fontWeight:'800'},more:{paddingVertical:10}});