import { useCallback, useEffect, useMemo, useState, type Dispatch, type SetStateAction } from 'react';
import { ActivityIndicator, Button, Pressable, ScrollView, Text, TextInput, View, type ViewStyle } from 'react-native';
import { Redirect } from 'expo-router';
import { createSuccessionRule, executeSuccession, listExperiences, listKnowledge, listMemories, listSuccessionRules, type Experience, type Knowledge, type Memory, type SuccessionRule, type TransferSelection } from '../features/inheritance/inheritance-service';
import { loadJourneyEvents, type JourneyEvent } from '../features/journey/journey-service';
import { useAuth } from '../state/auth-context';

type ShInstance = { is_primary?: boolean; sh_id: string };

export default function SuccessionScreen() {
  const { session, context } = useAuth(); const current = (context?.shInstances as ShInstance[] | undefined)?.find((v: ShInstance) => v.is_primary) ?? (context?.shInstances as ShInstance[] | undefined)?.[0]; const currentShId = current?.sh_id ?? ''; const currentAccountId = context?.account.account_id ?? '';
  const [successorAccountId, setSuccessorAccountId] = useState(''); const [events, setEvents] = useState<JourneyEvent[]>([]); const [memories, setMemories] = useState<Memory[]>([]); const [knowledge, setKnowledge] = useState<Knowledge[]>([]); const [experiences, setExperiences] = useState<Experience[]>([]); const [rules, setRules] = useState<SuccessionRule[]>([]);
  const [selectedJourneyIds, setSelectedJourneyIds] = useState<string[]>([]); const [selectedMemoryIds, setSelectedMemoryIds] = useState<string[]>([]); const [selectedKnowledgeIds, setSelectedKnowledgeIds] = useState<string[]>([]); const [selectedExperienceIds, setSelectedExperienceIds] = useState<string[]>([]);
  const [notice, setNotice] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false);
  const refresh = useCallback(async () => { if (!currentShId) return; setLoading(true); setError(null); try { const [journey, m, k, e, r] = await Promise.all([loadJourneyEvents(currentShId), listMemories(), listKnowledge(), listExperiences(), listSuccessionRules()]); setEvents(journey); setMemories(m.filter(v => v.sh_id === currentShId && ['CANDIDATE','ACTIVE','UPDATED'].includes(v.lifecycle))); setKnowledge(k.filter(v => v.sh_id === currentShId && ['CANDIDATE','ACTIVE'].includes(v.lifecycle))); setExperiences(e.filter(v => v.sh_id === currentShId && v.lifecycle === 'ACTIVE')); setRules(r); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load succession data'); } finally { setLoading(false); } }, [currentShId]);
  useEffect(() => { void refresh(); }, [refresh]); if (!session) return <Redirect href="/login" />; if (!context || !current) return <ActivityIndicator />;
  const eligible = useMemo(() => events.filter(e => e.transfer_policy !== 'NON_TRANSFERABLE'), [events]); const eligibleMemories = memories.filter(v => v.transfer_policy === 'SUCCESSION'); const eligibleKnowledge = knowledge.filter(v => v.transfer_policy === 'SUCCESSION'); const eligibleExperiences = experiences.filter(v => v.transfer_policy === 'SUCCESSION');
  const mySuccessions = useMemo(() => rules.filter(rule => rule.successor_account_id === currentAccountId), [rules, currentAccountId]); const ownRules = useMemo(() => rules.filter(rule => rule.source_sh_id === currentShId), [rules, currentShId]);
  const totalSelected = selectedJourneyIds.length + selectedMemoryIds.length + selectedKnowledgeIds.length + selectedExperienceIds.length; const toggle = (id: string, setter: Dispatch<SetStateAction<string[]>>) => setter(ids => ids.includes(id) ? ids.filter(v => v !== id) : [...ids, id]);
  async function create() { setBusy(true); setError(null); setNotice(null); try { const scope: TransferSelection = { memory_ids: selectedMemoryIds, knowledge_ids: selectedKnowledgeIds, experience_ids: selectedExperienceIds, journey_event_ids: selectedJourneyIds }; const value = await createSuccessionRule({ sourceShId: currentShId, successorAccountId, scope }); setNotice(`Succession rule created: ${String((value as { succession_id?: string }).succession_id ?? value)}`); setSuccessorAccountId(''); await refresh(); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to create succession rule'); } finally { setBusy(false); } }
  async function execute(successionId: string) { setBusy(true); setError(null); setNotice(null); try { await executeSuccession(successionId); setNotice(`Succession executed: ${successionId}`); await refresh(); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to execute succession'); } finally { setBusy(false); } }
  const card = (selected: boolean): ViewStyle => ({ borderWidth: 1, borderRadius: 10, padding: 12, borderColor: selected ? '#111827' : '#D1D5DB', backgroundColor: selected ? '#F3F4F6' : '#fff' });
  return <ScrollView contentContainerStyle={{ padding: 24, gap: 14 }}><Text style={{ fontSize: 28, fontWeight: '700' }}>Succession</Text><Text>Configure selected state now; materialization occurs only after the source reaches End-of-Life and the configured successor executes the authorized operation.</Text><Text style={{ fontWeight: '600' }}>Current account</Text><Text>{currentAccountId}</Text><Text style={{ fontWeight: '600' }}>Current SH</Text><Text>{currentShId}</Text><Text style={{ fontWeight: '600' }}>Successor account</Text><TextInput placeholder="Isi Account ID penerus" placeholderTextColor="#6B7280" value={successorAccountId} onChangeText={setSuccessorAccountId} style={{ borderWidth: 1, borderRadius: 8, padding: 12, color: '#111827', borderColor: '#111827' }} />{loading ? <ActivityIndicator /> : null}
    <ScopeList title="Memory records eligible for Succession" items={eligibleMemories.map(v => ({ id: v.memory_id, title: 'MEMORY', content: v.content, meta: `Scope: ${v.scope} / Visibility: ${v.visibility} / Policy: ${v.transfer_policy}` }))} selected={selectedMemoryIds} onToggle={id => toggle(id, setSelectedMemoryIds)} card={card} /><ScopeList title="Knowledge records eligible for Succession" items={eligibleKnowledge.map(v => ({ id: v.knowledge_id, title: 'KNOWLEDGE', content: v.content, meta: `Scope: ${v.scope} / Visibility: ${v.visibility} / Policy: ${v.transfer_policy}` }))} selected={selectedKnowledgeIds} onToggle={id => toggle(id, setSelectedKnowledgeIds)} card={card} /><ScopeList title="Experience records eligible for Succession" items={eligibleExperiences.map(v => ({ id: v.experience_id, title: 'EXPERIENCE', content: v.content, meta: `Scope: ${v.scope} / Visibility: ${v.visibility} / Policy: ${v.transfer_policy}` }))} selected={selectedExperienceIds} onToggle={id => toggle(id, setSelectedExperienceIds)} card={card} /><ScopeList title="Journey records eligible for Succession" items={eligible.map(v => ({ id: v.event_id, title: v.event_type, content: v.occurred_at, meta: `Policy: ${v.transfer_policy}` }))} selected={selectedJourneyIds} onToggle={id => toggle(id, setSelectedJourneyIds)} card={card} />
    <Button title={`Create succession rule (${totalSelected} selected)`} disabled={busy || !successorAccountId.trim() || totalSelected === 0} onPress={() => void create()} />{notice ? <Text>{notice}</Text> : null}{error ? <Text>{error}</Text> : null}
    <Text style={{ fontSize: 20, fontWeight: '700' }}>Configured succession rules</Text>{ownRules.length === 0 ? <Text>No succession rules configured by this account.</Text> : ownRules.map(rule => <ViewRule key={rule.succession_id} rule={rule} busy={busy} onExecute={execute} />)}
    <Text style={{ fontSize: 20, fontWeight: '700' }}>Successions available to this account</Text>{mySuccessions.length === 0 ? <Text>No succession rules are configured for this account.</Text> : mySuccessions.map(rule => <ViewRule key={`incoming-${rule.succession_id}`} rule={rule} busy={busy} onExecute={execute} />)}
  </ScrollView>;
}
function ViewRule({ rule, busy, onExecute }: { rule: SuccessionRule; busy: boolean; onExecute: (id: string) => void }) { return <View style={{ borderWidth: 1, padding: 12, borderRadius: 8, gap: 6 }}><Text>Succession: {rule.succession_id}</Text><Text>Source SH: {rule.source_sh_id}</Text><Text>Successor account: {rule.successor_account_id}</Text><Text>Status: {rule.status}</Text><Text>Scope: {JSON.stringify(rule.scope)}</Text>{rule.status === 'ACTIVE' ? <Button title="Execute succession" disabled={busy} onPress={() => onExecute(rule.succession_id)} /> : null}</View>; }
function ScopeList({ title, items, selected, onToggle, card }: { title: string; items: { id: string; title: string; content: string; meta: string }[]; selected: string[]; onToggle: (id: string) => void; card: (selected: boolean) => ViewStyle }) { return <><Text style={{ fontWeight: '600' }}>{title}</Text><Text>Owner-visible records are filtered here by the applicable transfer policy, not by privacy alone.</Text>{items.length === 0 ? <Text>No records are currently marked for this lifecycle.</Text> : null}{items.map(item => { const isSelected = selected.includes(item.id); return <Pressable key={item.id} onPress={() => onToggle(item.id)} style={card(isSelected)}><Text>{isSelected ? '☑' : '☐'} {item.title}</Text><Text>{item.content}</Text><Text>{item.meta}</Text></Pressable>; })}</>;
}
