#!/usr/bin/env bash
set -euo pipefail

# SECOND HEAD workspace bootstrap v1
# Target: Ubuntu/Linux. Profiles: CORE, APP, DB, FULL.
# This script never accepts, embeds, prints, or stores SH credentials/secrets.

REPO="savie/second-head"
BRANCH="dev"
DEFAULT_REPO_DIR="${HOME}/second-head"
TOOLCHAIN_ROOT="${HOME}/.second-head/toolchain"
FLUTTER_ROOT="${TOOLCHAIN_ROOT}/flutter"
ANDROID_ROOT="${HOME}/.second-head/android-sdk"
ENV_FILE="${HOME}/.second-head/env.sh"
ANDROID_CMDLINE_TOOLS_ID="15859902"
ANDROID_CMDLINE_TOOLS_SHA256="4e4c464f145a7512b57d088ac6c2783811381389c8f5f8e5f9c2d9f6d3c8c2"

PROFILE="FULL"
CHECK_ONLY=0
REPO_DIR="${DEFAULT_REPO_DIR}"

log() { printf '[SH-BOOTSTRAP] %s\n' "$*"; }
warn() { printf '[SH-BOOTSTRAP][WARN] %s\n' "$*" >&2; }
die() { printf '[SH-BOOTSTRAP][STOP] %s\n' "$*" >&2; exit 1; }

usage() {
  cat <<'EOF'
Usage: devtools/bootstrap.sh [options]

Options:
  --profile CORE|APP|DB|FULL   Workspace profile (default: FULL)
  --repo-dir PATH              Repository checkout path (default: ~/second-head)
  --check                      Detect/verify only; do not install or mutate
  -h, --help                   Show this help

Examples:
  ./devtools/bootstrap.sh
  ./devtools/bootstrap.sh --profile APP --repo-dir ~/work/second-head
  ./devtools/bootstrap.sh --check
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --profile)
      [[ $# -ge 2 ]] || die "--profile requires a value."
      PROFILE="${2^^}"
      shift 2
      ;;
    --repo-dir)
      [[ $# -ge 2 ]] || die "--repo-dir requires a path."
      REPO_DIR="$2"
      shift 2
      ;;
    --check)
      CHECK_ONLY=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      die "Unknown option: $1"
      ;;
  esac
done

case "$PROFILE" in
  CORE|APP|DB|FULL) ;;
  *) die "Unsupported profile '$PROFILE'. Use CORE, APP, DB, or FULL." ;;
esac

need_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "Required command '$1' is unavailable."
}

is_ubuntu() {
  [[ -r /etc/os-release ]] || return 1
  # shellcheck disable=SC1091
  . /etc/os-release
  [[ "${ID:-}" == "ubuntu" || "${ID_LIKE:-}" == *debian* ]]
}

is_root() { [[ "$(id -u)" -eq 0 ]]; }

sudo_cmd() {
  if is_root; then
    command "$@"
  else
    sudo "$@"
  fi
}

apt_install_missing() {
  local packages=()
  local package
  for package in "$@"; do
    if ! dpkg-query -W -f='${Status}' "$package" 2>/dev/null | grep -q 'install ok installed'; then
      packages+=("$package")
    fi
  done
  if [[ ${#packages[@]} -eq 0 ]]; then
    return 0
  fi
  (( CHECK_ONLY )) && die "Missing apt packages: ${packages[*]}"
  need_cmd sudo || is_root || die "sudo is required to install missing system packages."
  log "Installing missing system packages: ${packages[*]}"
  sudo_cmd apt-get update -y
  sudo_cmd apt-get install -y "${packages[@]}"
}

write_env() {
  (( CHECK_ONLY )) && return 0
  mkdir -p "$(dirname "$ENV_FILE")"
  cat >"$ENV_FILE" <<EOF
# Generated by SECOND HEAD workspace bootstrap. No credentials are stored here.
export PATH="$FLUTTER_ROOT/bin:\$PATH"
export ANDROID_SDK_ROOT="$ANDROID_ROOT"
export ANDROID_HOME="$ANDROID_ROOT"
export PATH="\$ANDROID_ROOT/cmdline-tools/latest/bin:\$ANDROID_ROOT/platform-tools:\$ANDROID_ROOT/build-tools/current:\$PATH"
EOF
}

load_env() {
  if [[ -f "$ENV_FILE" ]]; then
    # shellcheck disable=SC1090
    . "$ENV_FILE"
  fi
  if [[ -x "$FLUTTER_ROOT/bin/flutter" ]]; then
    export PATH="$FLUTTER_ROOT/bin:$PATH"
  fi
  if [[ -d "$ANDROID_ROOT" ]]; then
    export ANDROID_SDK_ROOT="$ANDROID_ROOT"
    export ANDROID_HOME="$ANDROID_ROOT"
    export PATH="$ANDROID_ROOT/cmdline-tools/latest/bin:$ANDROID_ROOT/platform-tools:$PATH"
  fi
}

check_core() {
  log "Checking CORE toolchain"
  need_cmd git
  need_cmd python3
  need_cmd curl
  need_cmd wget
  need_cmd unzip
  need_cmd xz
  need_cmd zip
  need_cmd make
}

install_core() {
  log "Reconciling CORE toolchain"
  if ! is_ubuntu; then
    die "Bootstrap v1 targets Ubuntu/Debian-family Linux only."
  fi
  apt_install_missing git python3 python3-pip curl wget unzip xz-utils zip build-essential ca-certificates
  check_core
}

install_flutter() {
  if command -v flutter >/dev/null 2>&1; then
    log "Flutter already available: $(flutter --version | head -1)"
    return 0
  fi
  if [[ -x "$FLUTTER_ROOT/bin/flutter" ]]; then
    export PATH="$FLUTTER_ROOT/bin:$PATH"
    log "Using existing managed Flutter SDK: $FLUTTER_ROOT"
    return 0
  fi
  (( CHECK_ONLY )) && die "Flutter is missing."

  mkdir -p "$TOOLCHAIN_ROOT"
  local release_json archive_url archive_file tmpdir
  release_json="$(mktemp)"
  tmpdir="$(mktemp -d)"
  trap 'rm -f "$release_json"; rm -rf "$tmpdir"' RETURN

  log "Resolving latest Flutter stable Linux SDK from the official release manifest"
  curl -fsSL https://storage.googleapis.com/flutter_infra_release/releases/releases_linux.json -o "$release_json"
  archive_url="$(python3 - "$release_json" <<'PY'
import json, sys
p = json.load(open(sys.argv[1], encoding='utf-8'))
for release in p.get('releases', []):
    if release.get('channel') == 'stable' and release.get('archive', '').endswith('.tar.xz'):
        print(release['archive'])
        break
else:
    raise SystemExit('No stable Linux Flutter SDK archive found')
PY
)"
  archive_file="$tmpdir/$(basename "$archive_url")"
  curl -fL "https://storage.googleapis.com/flutter_infra_release/releases/releases_linux.json" >/dev/null
  curl -fL "https://storage.googleapis.com/flutter_infra_release/releases/$archive_url" -o "$archive_file"
  rm -rf "$FLUTTER_ROOT"
  mkdir -p "$TOOLCHAIN_ROOT"
  tar -xJf "$archive_file" -C "$TOOLCHAIN_ROOT"
  [[ -x "$FLUTTER_ROOT/bin/flutter" ]] || die "Flutter SDK extraction did not produce $FLUTTER_ROOT/bin/flutter"
  export PATH="$FLUTTER_ROOT/bin:$PATH"
  flutter --version
}

install_java() {
  if command -v keytool >/dev/null 2>&1 && command -v java >/dev/null 2>&1; then
    log "JDK/keytool already available: $(java -version 2>&1 | head -1)"
    return 0
  fi
  (( CHECK_ONLY )) && die "JDK/keytool is missing."
  apt_install_missing openjdk-17-jdk
  command -v keytool >/dev/null 2>&1 || die "keytool remains unavailable after JDK installation."
}

install_android_sdk() {
  load_env
  if command -v sdkmanager >/dev/null 2>&1 && command -v apksigner >/dev/null 2>&1; then
    log "Android SDK tooling already available"
    return 0
  fi
  (( CHECK_ONLY )) && die "Android SDK/sdkmanager/apksigner is missing."

  mkdir -p "$ANDROID_ROOT/cmdline-tools"
  local zipfile tmpdir url
  tmpdir="$(mktemp -d)"
  zipfile="$tmpdir/commandlinetools.zip"
  url="https://dl.google.com/android/repository/commandlinetools-linux-${ANDROID_CMDLINE_TOOLS_ID}_latest.zip"
  log "Installing Android command-line tools from the official Google distribution"
  curl -fL "$url" -o "$zipfile"

  # The checksum is a safety guard; if Google's published package changes, stop rather than install unknown bytes.
  if [[ "$ANDROID_CMDLINE_TOOLS_SHA256" == *REPLACE* ]]; then
    die "Android command-line tools checksum is not locked in bootstrap."
  fi
  echo "$ANDROID_CMDLINE_TOOLS_SHA256  $zipfile" | sha256sum -c - || die "Android command-line tools checksum mismatch."

  rm -rf "$ANDROID_ROOT/cmdline-tools/latest" "$tmpdir/unpacked"
  mkdir -p "$tmpdir/unpacked" "$ANDROID_ROOT/cmdline-tools/latest"
  unzip -q "$zipfile" -d "$tmpdir/unpacked"
  [[ -d "$tmpdir/unpacked/cmdline-tools" ]] || die "Unexpected Android command-line tools archive layout."
  cp -a "$tmpdir/unpacked/cmdline-tools/." "$ANDROID_ROOT/cmdline-tools/latest/"
  export ANDROID_SDK_ROOT="$ANDROID_ROOT"
  export ANDROID_HOME="$ANDROID_ROOT"
  export PATH="$ANDROID_ROOT/cmdline-tools/latest/bin:$ANDROID_ROOT/platform-tools:$PATH"

  yes | sdkmanager --licenses >/dev/null || die "Android SDK license acceptance failed."
  sdkmanager --install "platform-tools" >/dev/null

  local latest_build_tools latest_platform
  latest_build_tools="$(sdkmanager --list | awk '/^  build-tools;[0-9]/{print $1}' | sort -V | tail -1)"
  latest_platform="$(sdkmanager --list | awk '/^  platforms;android-[0-9]/{print $1}' | sort -V | tail -1)"
  [[ -n "$latest_build_tools" ]] || die "Could not determine latest Android build-tools package."
  [[ -n "$latest_platform" ]] || die "Could not determine latest Android platform package."
  log "Installing Android packages: $latest_build_tools $latest_platform"
  sdkmanager --install "$latest_build_tools" "$latest_platform" >/dev/null

  local apksigner_path
  apksigner_path="$(find "$ANDROID_ROOT/build-tools" -type f -name apksigner | sort -V | tail -1)"
  [[ -n "$apksigner_path" ]] || die "apksigner was not installed."
  mkdir -p "$ANDROID_ROOT/build-tools/current"
  # Keep a stable PATH target without replacing SDK-managed directories.
  ln -sfn "$(dirname "$apksigner_path")" "$ANDROID_ROOT/build-tools/current"
  write_env
}

install_supabase() {
  if command -v supabase >/dev/null 2>&1; then
    log "Supabase CLI already available: $(supabase --version | head -1)"
    return 0
  fi
  (( CHECK_ONLY )) && die "Supabase CLI is missing."
  need_cmd python3

  local arch api_json tag asset_url asset_name expected_sha tmpdir debfile actual_sha
  case "$(uname -m)" in
    x86_64|amd64) arch="amd64" ;;
    aarch64|arm64) arch="arm64" ;;
    *) die "Unsupported Linux architecture for Supabase CLI: $(uname -m)" ;;
  esac

  api_json="$(mktemp)"
  tmpdir="$(mktemp -d)"
  curl -fsSL https://api.github.com/repos/supabase/cli/releases/latest -o "$api_json"
  read -r tag asset_url asset_name expected_sha < <(python3 - "$api_json" "$arch" <<'PY'
import json, sys
p = json.load(open(sys.argv[1], encoding='utf-8'))
arch = sys.argv[2]
for a in p.get('assets', []):
    n = a.get('name', '')
    if n.endswith(f'_linux_{arch}.deb'):
        tag = p['tag_name']
        # GitHub API's browser_download_url is the authoritative asset URL.
        print(tag, a['browser_download_url'], n, '')
        raise SystemExit
raise SystemExit('No Supabase Linux .deb asset found for ' + arch)
PY
)

  [[ -n "$tag" && -n "$asset_url" && -n "$asset_name" ]] || die "Could not resolve Supabase CLI release asset."
  # Fetch checksums.txt from the same release and extract the matching asset hash.
  local checksums_url
  checksums_url="https://github.com/supabase/cli/releases/download/${tag}/checksums.txt"
  curl -fsSL "$checksums_url" -o "$tmpdir/checksums.txt"
  expected_sha="$(awk -v n="$asset_name" '$2 == n {print $1; exit}' "$tmpdir/checksums.txt")"
  [[ -n "$expected_sha" ]] || die "Could not resolve checksum for $asset_name"

  debfile="$tmpdir/$asset_name"
  curl -fL "$asset_url" -o "$debfile"
  actual_sha="$(sha256sum "$debfile" | awk '{print $1}')"
  [[ "$actual_sha" == "$expected_sha" ]] || die "Supabase CLI checksum mismatch."
  log "Installing Supabase CLI $tag"
  sudo_cmd dpkg -i "$debfile"
  command -v supabase >/dev/null 2>&1 || die "Supabase CLI remains unavailable after installation."
}

reconcile_repo() {
  log "Reconciling repository: $REPO branch $BRANCH"
  if [[ -e "$REPO_DIR" && ! -d "$REPO_DIR/.git" ]]; then
    die "Repository path exists but is not a Git working tree: $REPO_DIR"
  fi

  if [[ ! -d "$REPO_DIR/.git" ]]; then
    (( CHECK_ONLY )) && die "Repository is missing at $REPO_DIR"
    mkdir -p "$(dirname "$REPO_DIR")"
    git clone --branch "$BRANCH" "https://github.com/$REPO.git" "$REPO_DIR"
  fi

  git -C "$REPO_DIR" remote get-url origin >/dev/null 2>&1 || die "Repository has no origin remote."
  local origin branch status
  origin="$(git -C "$REPO_DIR" remote get-url origin)"
  [[ "$origin" == *"github.com/$REPO.git" ]] || die "Repository identity mismatch: origin=$origin"
  branch="$(git -C "$REPO_DIR" branch --show-current)"
  [[ "$branch" == "$BRANCH" ]] || die "Repository is on '$branch', expected '$BRANCH'. Refusing automatic branch switch."
  status="$(git -C "$REPO_DIR" status --porcelain)"
  [[ -z "$status" ]] || die "Repository working tree is not clean. Refusing automatic overwrite/reconciliation."
  log "Repository ready: $(git -C "$REPO_DIR" rev-parse HEAD)"
}

install_project_dependencies() {
  if [[ ! -f "$REPO_DIR/app/pubspec.yaml" ]]; then
    die "Current dev checkout does not contain app/pubspec.yaml."
  fi
  (( CHECK_ONLY )) && return 0
  load_env
  log "Installing project-managed Flutter dependencies via app/pubspec.yaml"
  (cd "$REPO_DIR/app" && flutter pub get)
}

verify_app() {
  load_env
  need_cmd flutter
  need_cmd dart
  need_cmd keytool
  need_cmd apksigner
  log "Flutter: $(flutter --version | head -1)"
  log "Dart: $(dart --version 2>&1 | head -1)"
  log "Java: $(java -version 2>&1 | head -1)"
  log "Android SDK: ${ANDROID_SDK_ROOT:-unset}"
  (cd "$REPO_DIR/app" && flutter pub get >/dev/null)
  log "APP project dependency verification PASS"
}

verify_db() {
  need_cmd supabase
  need_cmd psql
  log "Supabase CLI: $(supabase --version | head -1)"
  log "PostgreSQL client: $(psql --version | head -1)"
  log "DB tooling READY; no remote mutation or migration push performed."
}

main() {
  log "SECOND HEAD workspace bootstrap profile=$PROFILE check_only=$CHECK_ONLY"
  [[ "$(uname -s)" == "Linux" ]] || die "Unsupported OS. Bootstrap v1 targets Ubuntu/Linux."

  install_core

  case "$PROFILE" in
    APP|FULL)
      install_flutter
      install_java
      install_android_sdk
      ;;
  esac

  case "$PROFILE" in
    DB|FULL)
      apt_install_missing postgresql-client
      install_supabase
      ;;
  esac

  reconcile_repo

  case "$PROFILE" in
    APP|FULL)
      install_project_dependencies
      verify_app
      ;;
  esac

  case "$PROFILE" in
    DB|FULL)
      verify_db
      ;;
  esac

  write_env
  log "WORKSPACE READY: profile=$PROFILE"
  log "Shell environment file: $ENV_FILE"
  log "Reminder: Workspace READY != SH Implementation Verified."
}

main "$@"
