#!/usr/bin/env bash
set -euo pipefail

# SECOND HEAD workspace bootstrap v1
# Target: Ubuntu/Linux. Profiles: CORE, APP, DB, FULL.
# Never requests, embeds, prints, or stores SH credentials/secrets.

REPO="savie/second-head"
BRANCH="dev"
DEFAULT_REPO_DIR="${HOME}/second-head"
TOOLCHAIN_ROOT="${HOME}/.second-head/toolchain"
FLUTTER_ROOT="${TOOLCHAIN_ROOT}/flutter"
ANDROID_ROOT="${HOME}/.second-head/android-sdk"
ENV_FILE="${HOME}/.second-head/env.sh"
ANDROID_CMDLINE_TOOLS_ID="15859902"
ANDROID_CMDLINE_TOOLS_SHA256="4e4c464f145a7512b57d088ac6c278c03c9eea610886b35a5e0804e74eedf583"

PROFILE="FULL"
CHECK_ONLY=0
REPO_DIR="$DEFAULT_REPO_DIR"

log() { printf '[SH-BOOTSTRAP] %s\n' "$*"; }
die() { printf '[SH-BOOTSTRAP][STOP] %s\n' "$*" >&2; exit 1; }
need_cmd() { command -v "$1" >/dev/null 2>&1 || die "Required command '$1' is unavailable."; }
is_root() { [[ "$(id -u)" -eq 0 ]]; }
sudo_cmd() { if is_root; then command "$@"; else sudo "$@"; fi; }

usage() {
  cat <<'EOF2'
Usage: devtools/bootstrap.sh [options]

Options:
  --profile CORE|APP|DB|FULL   Workspace profile (default: FULL)
  --repo-dir PATH              Repository checkout path (default: ~/second-head)
  --check                      Detect/verify only; do not install or mutate
  -h, --help                   Show this help
EOF2
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --profile) [[ $# -ge 2 ]] || die "--profile requires a value."; PROFILE="${2^^}"; shift 2 ;;
    --repo-dir) [[ $# -ge 2 ]] || die "--repo-dir requires a path."; REPO_DIR="$2"; shift 2 ;;
    --check) CHECK_ONLY=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) die "Unknown option: $1" ;;
  esac
done
case "$PROFILE" in CORE|APP|DB|FULL) ;; *) die "Unsupported profile '$PROFILE'." ;; esac

is_ubuntu() {
  [[ -r /etc/os-release ]] || return 1
  # shellcheck disable=SC1091
  . /etc/os-release
  [[ "${ID:-}" == ubuntu || "${ID:-}" == debian || "${ID_LIKE:-}" == *debian* ]]
}

apt_install_missing() {
  local packages=() package
  for package in "$@"; do
    if ! dpkg-query -W -f='${Status}' "$package" 2>/dev/null | grep -q 'install ok installed'; then
      packages+=("$package")
    fi
  done
  [[ ${#packages[@]} -eq 0 ]] && return 0
  (( CHECK_ONLY )) && die "Missing apt packages: ${packages[*]}"
  if ! is_root; then need_cmd sudo; fi
  log "Installing missing system packages: ${packages[*]}"
  sudo_cmd apt-get update -y
  sudo_cmd apt-get install -y "${packages[@]}"
}

write_env() {
  (( CHECK_ONLY )) && return 0
  mkdir -p "$(dirname "$ENV_FILE")"
  cat >"$ENV_FILE" <<EOF2
# Generated by SECOND HEAD workspace bootstrap. No credentials are stored here.
export PATH="${FLUTTER_ROOT}/bin:\$PATH"
export ANDROID_SDK_ROOT="${ANDROID_ROOT}"
export ANDROID_HOME="${ANDROID_ROOT}"
export PATH="${ANDROID_ROOT}/cmdline-tools/latest/bin:${ANDROID_ROOT}/platform-tools:\$PATH"
EOF2
}

load_env() {
  [[ -f "$ENV_FILE" ]] && . "$ENV_FILE"
  [[ -x "$FLUTTER_ROOT/bin/flutter" ]] && export PATH="$FLUTTER_ROOT/bin:$PATH"
  if [[ -d "$ANDROID_ROOT" ]]; then
    export ANDROID_SDK_ROOT="$ANDROID_ROOT" ANDROID_HOME="$ANDROID_ROOT"
    export PATH="$ANDROID_ROOT/cmdline-tools/latest/bin:$ANDROID_ROOT/platform-tools:$PATH"
    local apksigner_path
    apksigner_path="$(find "$ANDROID_ROOT/build-tools" -type f -name apksigner 2>/dev/null | sort -V | tail -1 || true)"
    [[ -n "$apksigner_path" ]] && export PATH="$(dirname "$apksigner_path"):$PATH"
  fi
}

install_core() {
  is_ubuntu || die "Bootstrap v1 targets Ubuntu/Debian-family Linux only."
  apt_install_missing git python3 python3-pip curl wget unzip xz-utils zip build-essential ca-certificates
  for tool in git python3 curl wget unzip xz zip make; do need_cmd "$tool"; done
}

install_flutter() {
  if command -v flutter >/dev/null 2>&1; then log "Flutter already available: $(flutter --version | head -1)"; return; fi
  if [[ -x "$FLUTTER_ROOT/bin/flutter" ]]; then export PATH="$FLUTTER_ROOT/bin:$PATH"; return; fi
  (( CHECK_ONLY )) && die "Flutter is missing."
  mkdir -p "$TOOLCHAIN_ROOT"
  local manifest archive_url archive_file tmpdir
  manifest="$(mktemp)"; tmpdir="$(mktemp -d)"
  curl -fsSL https://storage.googleapis.com/flutter_infra_release/releases/releases_linux.json -o "$manifest"
  archive_url="$(python3 - "$manifest" <<'PY'
import json, sys
p=json.load(open(sys.argv[1], encoding='utf-8'))
for r in p.get('releases', []):
    if r.get('channel') == 'stable' and r.get('archive','').endswith('.tar.xz'):
        print(r['archive']); break
else: raise SystemExit('No stable Linux Flutter SDK archive found')
PY
)"
  archive_file="$tmpdir/$(basename "$archive_url")"
  curl -fL "https://storage.googleapis.com/flutter_infra_release/releases/$archive_url" -o "$archive_file"
  rm -rf "$FLUTTER_ROOT"
  tar -xJf "$archive_file" -C "$TOOLCHAIN_ROOT"
  rm -rf "$manifest" "$tmpdir"
  [[ -x "$FLUTTER_ROOT/bin/flutter" ]] || die "Flutter SDK installation failed."
  export PATH="$FLUTTER_ROOT/bin:$PATH"
  flutter --version >/dev/null
}

install_java() {
  if command -v java >/dev/null 2>&1 && command -v keytool >/dev/null 2>&1; then return; fi
  (( CHECK_ONLY )) && die "JDK/keytool is missing."
  apt_install_missing openjdk-17-jdk
  need_cmd java; need_cmd keytool
}

install_android_sdk() {
  load_env
  if command -v sdkmanager >/dev/null 2>&1 && command -v apksigner >/dev/null 2>&1; then return; fi
  (( CHECK_ONLY )) && die "Android SDK/sdkmanager/apksigner is missing."
  mkdir -p "$ANDROID_ROOT/cmdline-tools"
  local tmpdir zipfile url
  tmpdir="$(mktemp -d)"; zipfile="$tmpdir/commandlinetools.zip"
  url="https://dl.google.com/android/repository/commandlinetools-linux-${ANDROID_CMDLINE_TOOLS_ID}_latest.zip"
  curl -fL "$url" -o "$zipfile"
  echo "$ANDROID_CMDLINE_TOOLS_SHA256  $zipfile" | sha256sum -c - || die "Android command-line tools checksum mismatch."
  rm -rf "$ANDROID_ROOT/cmdline-tools/latest" "$tmpdir/unpacked"
  mkdir -p "$ANDROID_ROOT/cmdline-tools/latest" "$tmpdir/unpacked"
  unzip -q "$zipfile" -d "$tmpdir/unpacked"
  [[ -d "$tmpdir/unpacked/cmdline-tools" ]] || die "Unexpected Android command-line tools archive layout."
  cp -a "$tmpdir/unpacked/cmdline-tools/." "$ANDROID_ROOT/cmdline-tools/latest/"
  export ANDROID_SDK_ROOT="$ANDROID_ROOT" ANDROID_HOME="$ANDROID_ROOT"
  export PATH="$ANDROID_ROOT/cmdline-tools/latest/bin:$ANDROID_ROOT/platform-tools:$PATH"
  log "Android SDK license acceptance is required for installation."
  set +o pipefail
  yes | sdkmanager --licenses >/dev/null
  local licenses_status=${PIPESTATUS[1]}
  set -o pipefail
  [[ "$licenses_status" -eq 0 ]] || die "Android SDK license acceptance failed (sdkmanager exit=$licenses_status)."
  sdkmanager --install platform-tools >/dev/null
  local build_tools platform apksigner_path
  build_tools="$(sdkmanager --list | awk '/^  build-tools;[0-9]/{print $1}' | sort -V | tail -1)"
  platform="$(sdkmanager --list | awk '/^  platforms;android-[0-9]/{print $1}' | sort -V | tail -1)"
  [[ -n "$build_tools" && -n "$platform" ]] || die "Could not determine Android SDK packages."
  sdkmanager --install "$build_tools" "$platform" >/dev/null
  apksigner_path="$(find "$ANDROID_ROOT/build-tools" -type f -name apksigner | sort -V | tail -1)"
  [[ -n "$apksigner_path" ]] || die "apksigner was not installed."
  write_env
  rm -rf "$tmpdir"
}

install_supabase() {
  command -v supabase >/dev/null 2>&1 && return
  (( CHECK_ONLY )) && die "Supabase CLI is missing."
  local arch api_json tag asset_url asset_name tmpdir checksums expected_sha debfile actual_sha
  case "$(uname -m)" in x86_64|amd64) arch=amd64 ;; aarch64|arm64) arch=arm64 ;; *) die "Unsupported Linux architecture: $(uname -m)" ;; esac
  api_json="$(mktemp)"; tmpdir="$(mktemp -d)"
  curl -fsSL https://api.github.com/repos/supabase/cli/releases/latest -o "$api_json"
  read -r tag asset_url asset_name < <(python3 - "$api_json" "$arch" <<'PY'
import json, sys
p=json.load(open(sys.argv[1], encoding='utf-8')); arch=sys.argv[2]
for a in p.get('assets', []):
    n=a.get('name','')
    if n.endswith(f'_linux_{arch}.deb'):
        print(p['tag_name'], a['browser_download_url'], n); break
else: raise SystemExit('No Supabase Linux .deb asset found')
PY
)
  [[ -n "$tag" && -n "$asset_url" && -n "$asset_name" ]] || die "Could not resolve Supabase CLI release asset."
  checksums="$tmpdir/checksums.txt"
  curl -fsSL "https://github.com/supabase/cli/releases/download/${tag}/checksums.txt" -o "$checksums"
  expected_sha="$(awk -v n="$asset_name" '$2 == n {print $1; exit}' "$checksums")"
  [[ -n "$expected_sha" ]] || die "Could not resolve checksum for $asset_name"
  debfile="$tmpdir/$asset_name"
  curl -fL "$asset_url" -o "$debfile"
  actual_sha="$(sha256sum "$debfile" | awk '{print $1}')"
  [[ "$actual_sha" == "$expected_sha" ]] || die "Supabase CLI checksum mismatch."
  sudo_cmd dpkg -i "$debfile"
  rm -rf "$api_json" "$tmpdir"
  need_cmd supabase
}

is_expected_workspace_artifact() {
  case "$1" in
    "?? app/.dart_tool/"|"?? app/pubspec.lock") return 0 ;;
    *) return 1 ;;
  esac
}

reconcile_repo() {
  if [[ -e "$REPO_DIR" && ! -d "$REPO_DIR/.git" ]]; then die "Repository path exists but is not a Git working tree: $REPO_DIR"; fi
  if [[ ! -d "$REPO_DIR/.git" ]]; then
    (( CHECK_ONLY )) && die "Repository is missing at $REPO_DIR"
    mkdir -p "$(dirname "$REPO_DIR")"
    git clone --branch "$BRANCH" "https://github.com/$REPO.git" "$REPO_DIR"
  fi
  local origin branch status unexpected line
  origin="$(git -C "$REPO_DIR" remote get-url origin 2>/dev/null)" || die "Repository has no origin remote."
  [[ "$origin" == *"github.com/$REPO.git" ]] || die "Repository identity mismatch: origin=$origin"
  branch="$(git -C "$REPO_DIR" branch --show-current)"
  [[ "$branch" == "$BRANCH" ]] || die "Repository is on '$branch', expected '$BRANCH'. Refusing automatic branch switch."
  status="$(git -C "$REPO_DIR" status --porcelain)"
  unexpected=""
  while IFS= read -r line; do
    [[ -z "$line" ]] && continue
    if ! is_expected_workspace_artifact "$line"; then
      unexpected+="$line\n"
    fi
  done <<< "$status"
  if [[ -n "$unexpected" ]]; then
    printf '%b' "$unexpected" >&2
    die "Repository working tree contains unexpected changes. Refusing automatic overwrite/reconciliation."
  fi
  [[ -z "$status" ]] || log "Ignoring expected Flutter workspace artifacts in repository: $(printf '%s' "$status" | tr '\n' ' ')"
  log "Repository ready: $(git -C "$REPO_DIR" rev-parse HEAD)"
}

install_project_dependencies() {
  [[ -f "$REPO_DIR/app/pubspec.yaml" ]] || die "Current dev checkout does not contain app/pubspec.yaml."
  (( CHECK_ONLY )) && return
  load_env
  (cd "$REPO_DIR/app" && flutter pub get)
}

verify_app() {
  load_env
  need_cmd flutter; need_cmd dart; need_cmd keytool; need_cmd apksigner
  log "Flutter: $(flutter --version | head -1)"
  log "Dart: $(dart --version 2>&1 | head -1)"
  log "Java: $(java -version 2>&1 | head -1)"
  log "Android SDK: ${ANDROID_SDK_ROOT:-unset}"
}

verify_db() {
  need_cmd supabase; need_cmd psql
  log "Supabase CLI: $(supabase --version | head -1)"
  log "PostgreSQL client: $(psql --version | head -1)"
  log "DB tooling READY; no remote mutation or migration push performed."
}

main() {
  [[ "$(uname -s)" == Linux ]] || die "Unsupported OS. Bootstrap v1 targets Ubuntu/Linux."
  install_core
  case "$PROFILE" in APP|FULL) install_flutter; install_java; install_android_sdk ;; esac
  case "$PROFILE" in DB|FULL) apt_install_missing postgresql-client; install_supabase ;; esac
  reconcile_repo
  case "$PROFILE" in APP|FULL) install_project_dependencies; verify_app ;; esac
  case "$PROFILE" in DB|FULL) verify_db ;; esac
  write_env
  log "WORKSPACE READY: profile=$PROFILE"
  log "Environment file: $ENV_FILE"
  log "Workspace READY != SH Implementation Verified."
}

main "$@"
