import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const PROTOCOL_VERSION="2025-11-25"; const jsonHeaders={"Content-Type":"application/json","Cache-Control":"no-store"};
type JsonRpc={jsonrpc?:string;id?:string|number|null;method?:string;params?:Record<string,unknown>};
function rpc(id:JsonRpc["id"],result:Record<string,unknown>){return new Response(JSON.stringify({jsonrpc:"2.0",id,result}),{status:200,headers:jsonHeaders});}
function err(id:JsonRpc["id"],code:number,message:string,data?:unknown){return new Response(JSON.stringify({jsonrpc:"2.0",id,error:{code,message,...(data===undefined?{}:{data})}}),{status:200,headers:jsonHeaders});}
function validOrigin(req:Request){const origin=req.headers.get("Origin");if(!origin)return true;const allowed=(Deno.env.get("R8_MCP_ALLOWED_ORIGINS")??"").split(",").map(x=>x.trim()).filter(Boolean);return allowed.includes(origin);}
function youtubeUrl(id:string){return "https://www.youtube.com/watch?v="+encodeURIComponent(id);}
async function youtubeApi(path:string,params:Record<string,string>){const key=Deno.env.get("YOUTUBE_API_KEY");if(!key)throw new Error("R8_YOUTUBE_CONFIGURATION_ERROR");const url=new URL("https://www.googleapis.com/youtube/v3/"+path);url.searchParams.set("key",key);for(const [k,v] of Object.entries(params))url.searchParams.set(k,v);const response=await fetch(url,{headers:{Accept:"application/json"}});if(response.status===404)throw new Error("R8_YOUTUBE_NOT_FOUND");if(response.status===403)throw new Error("R8_YOUTUBE_PROVIDER_REJECTED");if(response.status===429)throw new Error("R8_YOUTUBE_QUOTA_EXCEEDED");if(!response.ok)throw new Error("R8_YOUTUBE_PROVIDER_HTTP_"+response.status);return await response.json() as Record<string,unknown>;}
async function searchYouTube(args:Record<string,unknown>){const query=typeof args.query==="string"?args.query.trim():"";const maxResults=Math.min(Math.max(Number(args.max_results??5),1),10);if(!query)throw new Error("R8_YOUTUBE_INVALID_INPUT");const data=await youtubeApi("search",{part:"snippet",q:query,type:"video",order:"relevance",maxResults:String(maxResults)});const items=Array.isArray(data.items)?data.items:[];return items.map((item:any)=>({video_id:item?.id?.videoId,title:item?.snippet?.title,channel_title:item?.snippet?.channelTitle,published_at:item?.snippet?.publishedAt,thumbnail_url:item?.snippet?.thumbnails?.high?.url??item?.snippet?.thumbnails?.default?.url,youtube_url:item?.id?.videoId?youtubeUrl(item.id.videoId):undefined})).filter((x:any)=>typeof x.video_id==="string");}
async function getVideo(args:Record<string,unknown>){const videoId=typeof args.video_id==="string"?args.video_id.trim():"";if(!videoId||!/^[A-Za-z0-9_-]{6,20}$/.test(videoId))throw new Error("R8_YOUTUBE_INVALID_INPUT");const data=await youtubeApi("videos",{part:"snippet,contentDetails,statistics",id:videoId});const item:any=Array.isArray(data.items)?data.items[0]:undefined;if(!item)throw new Error("R8_YOUTUBE_NOT_FOUND");return {provider:"YOUTUBE",video_id:videoId,title:item.snippet?.title,channel_id:item.snippet?.channelId,channel_title:item.snippet?.channelTitle,published_at:item.snippet?.publishedAt,description:item.snippet?.description,duration:item.contentDetails?.duration,view_count:item.statistics?.viewCount,like_count:item.statistics?.likeCount,youtube_url:youtubeUrl(videoId)};}
const tools=[{name:"youtube_search",title:"Search YouTube",description:"Search public YouTube videos. Read-only.",inputSchema:{type:"object",properties:{query:{type:"string",minLength:1},max_results:{type:"integer",minimum:1,maximum:10,default:5}},required:["query"]},annotations:{readOnlyHint:true,destructiveHint:false}},{name:"youtube_get_video",title:"Get YouTube Video",description:"Get public metadata for one YouTube video. Read-only.",inputSchema:{type:"object",properties:{video_id:{type:"string",minLength:6,maxLength:20}},required:["video_id"]},annotations:{readOnlyHint:true,destructiveHint:false}}];
Deno.serve(async(req:Request)=>{if(!validOrigin(req))return new Response(JSON.stringify({error:"R8_MCP_ORIGIN_REJECTED"}),{status:403,headers:jsonHeaders});if(req.method==="GET")return new Response(null,{status:405,headers:{Allow:"POST",...jsonHeaders}});if(req.method!=="POST")return new Response(JSON.stringify({error:"METHOD_NOT_ALLOWED"}),{status:405,headers:jsonHeaders});const accept=req.headers.get("Accept")??"";if(!accept.includes("application/json")||!accept.includes("text/event-stream"))return new Response(JSON.stringify({error:"R8_MCP_ACCEPT_REQUIRED"}),{status:406,headers:jsonHeaders});const version=req.headers.get("MCP-Protocol-Version");if(version&&version!==PROTOCOL_VERSION)return err(null,-32602,"Unsupported protocol version",{supported:[PROTOCOL_VERSION],requested:version});let body:JsonRpc;try{body=await req.json();}catch{return err(null,-32700,"Parse error");}if(body.jsonrpc!=="2.0"||!body.method)return err(body.id??null,-32600,"Invalid Request");try{switch(body.method){case"initialize":return rpc(body.id,{protocolVersion:PROTOCOL_VERSION,capabilities:{tools:{listChanged:false}},serverInfo:{name:"second-head-r8-youtube",version:"1.0.0",description:"SH-controlled read-only YouTube MCP capability"}});case"notifications/initialized":return new Response(null,{status:202});case"tools/list":return rpc(body.id,{tools});case"tools/call":{const params=body.params??{};const name=typeof params.name==="string"?params.name:"";const args=(params.arguments&&typeof params.arguments==="object"?params.arguments:{}) as Record<string,unknown>;if(name==="youtube_search"){const result=await searchYouTube(args);return rpc(body.id,{content:[{type:"text",text:JSON.stringify(result)}],structuredContent:{results:result},isError:false});}if(name==="youtube_get_video"){const result=await getVideo(args);return rpc(body.id,{content:[{type:"text",text:JSON.stringify(result)}],structuredContent:result,isError:false});}return err(body.id,-32602,"Unknown tool",{name});}default:return err(body.id,-32601,"Method not found",{method:body.method});}}catch(e){const message=e instanceof Error?e.message:"R8_YOUTUBE_PROVIDER_ERROR";return rpc(body.id,{content:[{type:"text",text:message}],isError:true});}});
