CREATE OR REPLACE FUNCTION public.runtime_restore_recovery_snapshot(p_snapshot_id uuid)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_snapshot public.recovery_snapshots%rowtype;
  v_recovery_event_id uuid;
  v_existing_event public.recovery_events%rowtype;
  v_sh_id uuid; v_identity uuid;
  v_state jsonb; v_state_sh_id uuid; v_snapshot_state_version integer; v_snapshot_revision bigint; v_snapshot_payload jsonb; v_current_state_version integer;
  v_missing_before integer:=0; v_missing_after integer:=0; v_attachment_missing_after integer:=0;
  v_continuity_status text; v_gap_code text:=null;
BEGIN
  SELECT * INTO v_snapshot FROM public.recovery_snapshots WHERE snapshot_id=p_snapshot_id AND account_id=public.current_account_id() FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'RECOVERY_REJECTED: snapshot not accessible'; END IF;
  IF EXISTS (SELECT 1 FROM public.sh_instances s WHERE s.sh_id=v_snapshot.sh_id AND s.account_id=public.current_account_id() AND s.status='deactivated') THEN RAISE EXCEPTION 'RECOVERY_REJECTED: SH is terminal/deactivated'; END IF;
  SELECT * INTO v_existing_event FROM public.recovery_events WHERE snapshot_id=p_snapshot_id FOR UPDATE;
  IF FOUND THEN RETURN v_existing_event.recovery_event_id; END IF;

  v_sh_id:=v_snapshot.sh_id; v_identity:=(v_snapshot.manifest->'identity_root'->>'sh_id')::uuid;
  IF v_identity<>v_sh_id THEN RAISE EXCEPTION 'RECOVERY_REJECTED: identity root mismatch'; END IF;
  IF NOT EXISTS (SELECT 1 FROM public.sh_instances WHERE sh_id=v_sh_id AND account_id=public.current_account_id()) THEN RAISE EXCEPTION 'RECOVERY_REJECTED: target SH ownership mismatch'; END IF;
  v_state:=v_snapshot.manifest->'state';
  IF v_state IS NULL OR jsonb_typeof(v_state)<>'object' THEN RAISE EXCEPTION 'RECOVERY_REJECTED: State missing from snapshot'; END IF;
  v_state_sh_id:=(v_state->>'sh_id')::uuid;
  IF v_state_sh_id<>v_sh_id THEN RAISE EXCEPTION 'RECOVERY_REJECTED: State identity mismatch'; END IF;
  v_snapshot_state_version:=(v_state->>'state_version')::integer; v_snapshot_revision:=(v_state->>'revision')::bigint; v_snapshot_payload:=v_state->'state_payload';
  IF v_snapshot_state_version IS NULL OR v_snapshot_state_version<=0 THEN RAISE EXCEPTION 'RECOVERY_REJECTED: invalid State version'; END IF;
  IF v_snapshot_revision IS NULL OR v_snapshot_revision<=0 THEN RAISE EXCEPTION 'RECOVERY_REJECTED: invalid State revision'; END IF;
  IF jsonb_typeof(v_snapshot_payload)<>'object' THEN RAISE EXCEPTION 'RECOVERY_REJECTED: invalid State payload'; END IF;
  SELECT state_version INTO v_current_state_version FROM public.sh_states WHERE sh_id=v_sh_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'RECOVERY_REJECTED: target SH State not found'; END IF;
  IF v_snapshot_state_version<>v_current_state_version THEN RAISE EXCEPTION 'UNSUPPORTED_STATE_VERSION'; END IF;

  SELECT coalesce((select count(*) from jsonb_to_recordset(coalesce(v_snapshot.manifest->'ownership_root','[]'::jsonb)) x(ownership_id uuid,account_id uuid,sh_id uuid) where x.sh_id=v_sh_id and x.account_id=public.current_account_id() and not exists(select 1 from public.sh_ownership o where o.ownership_id=x.ownership_id)),0)
    +coalesce((select count(*) from jsonb_to_recordset(coalesce(v_snapshot.manifest->'memories','[]'::jsonb)) x(memory_id uuid,sh_id uuid) where x.sh_id=v_sh_id and not exists(select 1 from public.memories m where m.memory_id=x.memory_id)),0)
    +coalesce((select count(*) from jsonb_to_recordset(coalesce(v_snapshot.manifest->'conversations','[]'::jsonb)) x(conversation_id uuid,account_id uuid,sh_id uuid) where x.sh_id=v_sh_id and x.account_id=public.current_account_id() and not exists(select 1 from public.conversations c where c.conversation_id=x.conversation_id)),0)
    +coalesce((select count(*) from jsonb_to_recordset(coalesce(v_snapshot.manifest->'journey_events','[]'::jsonb)) x(event_id uuid,account_id uuid,sh_id uuid) where x.sh_id=v_sh_id and x.account_id=public.current_account_id() and not exists(select 1 from public.journey_events j where j.event_id=x.event_id)),0)
    +coalesce((select count(*) from jsonb_to_recordset(coalesce(v_snapshot.manifest->'knowledge','[]'::jsonb)) x(knowledge_id uuid,sh_id uuid,scope text) where x.sh_id=v_sh_id and x.scope='PRIVATE' and not exists(select 1 from public.knowledge k where k.knowledge_id=x.knowledge_id)),0)
    +coalesce((select count(*) from jsonb_to_recordset(coalesce(v_snapshot.manifest->'experiences','[]'::jsonb)) x(experience_id uuid,sh_id uuid,account_id uuid) where x.sh_id=v_sh_id and x.account_id=public.current_account_id() and not exists(select 1 from public.experiences e where e.experience_id=x.experience_id)),0)
    +coalesce((select count(*) from jsonb_to_recordset(coalesce(v_snapshot.manifest->'legacy_records','[]'::jsonb)) x(legacy_id uuid,source_sh_id uuid) where x.source_sh_id=v_sh_id and not exists(select 1 from public.legacy_records l where l.legacy_id=x.legacy_id)),0) INTO v_missing_before;

  INSERT INTO public.projects(project_id,account_id,sh_id,name,metadata,created_at,updated_at) SELECT x.project_id,x.account_id,x.sh_id,x.name,x.metadata,x.created_at,x.updated_at FROM jsonb_to_recordset(coalesce(v_snapshot.manifest->'projects','[]'::jsonb)) x(project_id uuid,account_id uuid,sh_id uuid,name text,metadata jsonb,created_at timestamptz,updated_at timestamptz) WHERE x.sh_id=v_sh_id AND x.account_id=public.current_account_id() ON CONFLICT(project_id) DO UPDATE SET account_id=excluded.account_id,sh_id=excluded.sh_id,name=excluded.name,metadata=excluded.metadata,created_at=excluded.created_at,updated_at=excluded.updated_at;
  INSERT INTO public.conversation_threads(conversation_id,account_id,sh_id,project_id,title,created_at,updated_at) SELECT x.conversation_id,x.account_id,x.sh_id,x.project_id,x.title,x.created_at,x.updated_at FROM jsonb_to_recordset(coalesce(v_snapshot.manifest->'conversation_threads','[]'::jsonb)) x(conversation_id uuid,account_id uuid,sh_id uuid,project_id uuid,title text,created_at timestamptz,updated_at timestamptz) WHERE x.sh_id=v_sh_id AND x.account_id=public.current_account_id() AND (x.project_id IS NULL OR EXISTS(select 1 from public.projects p where p.project_id=x.project_id and p.sh_id=v_sh_id and p.account_id=public.current_account_id())) ON CONFLICT(conversation_id) DO UPDATE SET account_id=excluded.account_id,sh_id=excluded.sh_id,project_id=excluded.project_id,title=excluded.title,created_at=excluded.created_at,updated_at=excluded.updated_at;
  INSERT INTO public.sh_ownership(ownership_id,account_id,sh_id,role,granted_at,evidence_ref,created_at) SELECT x.ownership_id,x.account_id,x.sh_id,x.role,x.granted_at,x.evidence_ref,x.created_at FROM jsonb_to_recordset(coalesce(v_snapshot.manifest->'ownership_root','[]'::jsonb)) x(ownership_id uuid,account_id uuid,sh_id uuid,role text,granted_at timestamptz,evidence_ref text,created_at timestamptz) WHERE x.sh_id=v_sh_id AND x.account_id=public.current_account_id() ON CONFLICT(ownership_id) DO NOTHING;
  INSERT INTO public.memories(memory_id,sh_id,memory_type,content,source,confidence,scope,visibility,lifecycle,occurrence_count,created_at,updated_at,superseded_by,transfer_policy,provenance) SELECT x.memory_id,x.sh_id,x.memory_type,x.content,x.source,x.confidence,x.scope,x.visibility,x.lifecycle,x.occurrence_count,x.created_at,x.updated_at,x.superseded_by,x.transfer_policy,x.provenance FROM jsonb_to_recordset(coalesce(v_snapshot.manifest->'memories','[]'::jsonb)) x(memory_id uuid,sh_id uuid,memory_type text,content text,source text,confidence numeric,scope text,visibility text,lifecycle text,occurrence_count integer,created_at timestamptz,updated_at timestamptz,superseded_by uuid,transfer_policy text,provenance jsonb) WHERE x.sh_id=v_sh_id ON CONFLICT(memory_id) DO UPDATE SET sh_id=excluded.sh_id,memory_type=excluded.memory_type,content=excluded.content,source=excluded.source,confidence=excluded.confidence,scope=excluded.scope,visibility=excluded.visibility,lifecycle=excluded.lifecycle,occurrence_count=excluded.occurrence_count,created_at=excluded.created_at,updated_at=excluded.updated_at,superseded_by=excluded.superseded_by,transfer_policy=excluded.transfer_policy,provenance=excluded.provenance;
  INSERT INTO public.conversations(conversation_id,account_id,sh_id,role,content,created_at,metadata,thread_id,message_id) SELECT x.conversation_id,x.account_id,x.sh_id,x.role,x.content,x.created_at,x.metadata,x.thread_id,x.message_id FROM jsonb_to_recordset(coalesce(v_snapshot.manifest->'conversations','[]'::jsonb)) x(conversation_id uuid,account_id uuid,sh_id uuid,role text,content text,created_at timestamptz,metadata jsonb,thread_id uuid,message_id uuid) WHERE x.sh_id=v_sh_id AND x.account_id=public.current_account_id() AND EXISTS(select 1 from public.conversation_threads t where t.conversation_id=x.thread_id and t.sh_id=v_sh_id and t.account_id=public.current_account_id()) ON CONFLICT(conversation_id) DO UPDATE SET account_id=excluded.account_id,sh_id=excluded.sh_id,role=excluded.role,content=excluded.content,created_at=excluded.created_at,metadata=excluded.metadata,thread_id=excluded.thread_id,message_id=excluded.message_id;
  INSERT INTO public.journey_events(event_id,sh_id,account_id,event_type,occurred_at,continuity_status,gap_code,payload,source_ref,created_at,visibility,transfer_policy,provenance) SELECT x.event_id,x.sh_id,x.account_id,x.event_type,x.occurred_at,x.continuity_status,x.gap_code,x.payload,x.source_ref,x.created_at,x.visibility,x.transfer_policy,x.provenance FROM jsonb_to_recordset(coalesce(v_snapshot.manifest->'journey_events','[]'::jsonb)) x(event_id uuid,sh_id uuid,account_id uuid,event_type text,occurred_at timestamptz,continuity_status text,gap_code text,payload jsonb,source_ref text,created_at timestamptz,visibility text,transfer_policy text,provenance jsonb) WHERE x.sh_id=v_sh_id AND x.account_id=public.current_account_id() ON CONFLICT(event_id) DO UPDATE SET sh_id=excluded.sh_id,account_id=excluded.account_id,event_type=excluded.event_type,occurred_at=excluded.occurred_at,continuity_status=excluded.continuity_status,gap_code=excluded.gap_code,payload=excluded.payload,source_ref=excluded.source_ref,created_at=excluded.created_at,visibility=excluded.visibility,transfer_policy=excluded.transfer_policy,provenance=excluded.provenance;
  INSERT INTO public.knowledge(knowledge_id,content,knowledge_class,scope,visibility,source,provenance,confidence,version,lifecycle,superseded_by,created_at,updated_at,sh_id,transfer_policy) SELECT x.knowledge_id,x.content,x.knowledge_class,x.scope,x.visibility,x.source,x.provenance,x.confidence,x.version,x.lifecycle,x.superseded_by,x.created_at,x.updated_at,x.sh_id,x.transfer_policy FROM jsonb_to_recordset(coalesce(v_snapshot.manifest->'knowledge','[]'::jsonb)) x(knowledge_id uuid,content text,knowledge_class text,scope text,visibility text,source text,provenance jsonb,confidence numeric,version integer,lifecycle text,superseded_by uuid,created_at timestamptz,updated_at timestamptz,sh_id uuid,transfer_policy text) WHERE x.sh_id=v_sh_id AND x.scope='PRIVATE' ON CONFLICT(knowledge_id) DO UPDATE SET content=excluded.content,knowledge_class=excluded.knowledge_class,scope=excluded.scope,visibility=excluded.visibility,source=excluded.source,provenance=excluded.provenance,confidence=excluded.confidence,version=excluded.version,lifecycle=excluded.lifecycle,superseded_by=excluded.superseded_by,created_at=excluded.created_at,updated_at=excluded.updated_at,sh_id=excluded.sh_id,transfer_policy=excluded.transfer_policy;
  INSERT INTO public.experiences(experience_id,sh_id,account_id,experience_type,content,scope,visibility,source_ref,provenance,lifecycle,occurred_at,created_at,updated_at,transfer_policy) SELECT x.experience_id,x.sh_id,x.account_id,x.experience_type,x.content,x.scope,x.visibility,x.source_ref,x.provenance,x.lifecycle,x.occurred_at,x.created_at,x.updated_at,x.transfer_policy FROM jsonb_to_recordset(coalesce(v_snapshot.manifest->'experiences','[]'::jsonb)) x(experience_id uuid,sh_id uuid,account_id uuid,experience_type text,content text,scope text,visibility text,source_ref text,provenance jsonb,lifecycle text,occurred_at timestamptz,created_at timestamptz,updated_at timestamptz,transfer_policy text) WHERE x.sh_id=v_sh_id AND x.account_id=public.current_account_id() ON CONFLICT(experience_id) DO UPDATE SET sh_id=excluded.sh_id,account_id=excluded.account_id,experience_type=excluded.experience_type,content=excluded.content,scope=excluded.scope,visibility=excluded.visibility,source_ref=excluded.source_ref,provenance=excluded.provenance,lifecycle=excluded.lifecycle,occurred_at=excluded.occurred_at,created_at=excluded.created_at,updated_at=excluded.updated_at,transfer_policy=excluded.transfer_policy;
  INSERT INTO public.legacy_records(legacy_id,source_sh_id,legacy_type,payload,provenance,status,retention_until,created_at) SELECT x.legacy_id,x.source_sh_id,x.legacy_type,x.payload,x.provenance,x.status,x.retention_until,x.created_at FROM jsonb_to_recordset(coalesce(v_snapshot.manifest->'legacy_records','[]'::jsonb)) x(legacy_id uuid,source_sh_id uuid,legacy_type text,payload jsonb,provenance jsonb,status text,retention_until timestamptz,created_at timestamptz) WHERE x.source_sh_id=v_sh_id ON CONFLICT(legacy_id) DO UPDATE SET source_sh_id=excluded.source_sh_id,legacy_type=excluded.legacy_type,payload=excluded.payload,provenance=excluded.provenance,status=excluded.status,retention_until=excluded.retention_until,created_at=excluded.created_at;
  INSERT INTO public.conversation_attachment_recovery_refs(snapshot_id,attachment_id) SELECT p_snapshot_id,x.attachment_id FROM jsonb_to_recordset(coalesce(v_snapshot.manifest->'conversation_attachments','[]'::jsonb)) x(attachment_id uuid,message_id uuid) JOIN public.conversation_attachments a ON a.attachment_id=x.attachment_id AND a.account_id=public.current_account_id() AND a.sh_id=v_sh_id ON CONFLICT(snapshot_id,attachment_id) DO NOTHING;
  UPDATE public.conversation_attachments a SET message_id=x.message_id,updated_at=now() FROM jsonb_to_recordset(coalesce(v_snapshot.manifest->'conversation_attachments','[]'::jsonb)) x(attachment_id uuid,message_id uuid) WHERE a.attachment_id=x.attachment_id AND a.account_id=public.current_account_id() AND a.sh_id=v_sh_id AND a.status='PERSISTED' AND a.message_id IS NULL AND EXISTS(select 1 from public.conversations c where c.message_id=x.message_id and c.account_id=public.current_account_id() and c.sh_id=v_sh_id) AND EXISTS(select 1 from storage.objects o where o.bucket_id='second-head-conversation' and o.name=a.storage_ref);
  SELECT count(*) INTO v_attachment_missing_after FROM jsonb_to_recordset(coalesce(v_snapshot.manifest->'conversation_attachments','[]'::jsonb)) x(attachment_id uuid,message_id uuid,storage_ref text,status text) WHERE x.status='PERSISTED' AND (NOT EXISTS(select 1 from public.conversation_attachments a where a.attachment_id=x.attachment_id and a.account_id=public.current_account_id() and a.sh_id=v_sh_id and a.status='PERSISTED') OR NOT EXISTS(select 1 from storage.objects o where o.bucket_id='second-head-conversation' and o.name=x.storage_ref) OR NOT EXISTS(select 1 from public.conversations c where c.message_id=x.message_id and c.account_id=public.current_account_id() and c.sh_id=v_sh_id) OR EXISTS(select 1 from public.conversation_attachments a where a.attachment_id=x.attachment_id and a.message_id IS NOT NULL and a.message_id<>x.message_id));
  UPDATE public.sh_states SET state_payload=v_snapshot_payload,state_version=v_snapshot_state_version,revision=greatest(revision,v_snapshot_revision)+1,updated_at=now() WHERE sh_id=v_sh_id;
  SELECT coalesce((select count(*) from jsonb_to_recordset(coalesce(v_snapshot.manifest->'projects','[]'::jsonb)) x(project_id uuid,account_id uuid,sh_id uuid) where x.sh_id=v_sh_id and x.account_id=public.current_account_id() and not exists(select 1 from public.projects p where p.project_id=x.project_id)),0)+coalesce((select count(*) from jsonb_to_recordset(coalesce(v_snapshot.manifest->'conversation_threads','[]'::jsonb)) x(conversation_id uuid,account_id uuid,sh_id uuid) where x.sh_id=v_sh_id and x.account_id=public.current_account_id() and not exists(select 1 from public.conversation_threads t where t.conversation_id=x.conversation_id)),0)+coalesce((select count(*) from jsonb_to_recordset(coalesce(v_snapshot.manifest->'conversations','[]'::jsonb)) x(conversation_id uuid,account_id uuid,sh_id uuid,thread_id uuid) where x.sh_id=v_sh_id and x.account_id=public.current_account_id() and (not exists(select 1 from public.conversations c where c.conversation_id=x.conversation_id) or x.thread_id is null or not exists(select 1 from public.conversation_threads t where t.conversation_id=x.thread_id and t.sh_id=v_sh_id and t.account_id=public.current_account_id()))),0)+coalesce((select count(*) from jsonb_to_recordset(coalesce(v_snapshot.manifest->'ownership_root','[]'::jsonb)) x(ownership_id uuid,account_id uuid,sh_id uuid) where x.sh_id=v_sh_id and x.account_id=public.current_account_id() and not exists(select 1 from public.sh_ownership o where o.ownership_id=x.ownership_id)),0)+coalesce((select count(*) from jsonb_to_recordset(coalesce(v_snapshot.manifest->'memories','[]'::jsonb)) x(memory_id uuid,sh_id uuid) where x.sh_id=v_sh_id and not exists(select 1 from public.memories m where m.memory_id=x.memory_id)),0)+coalesce((select count(*) from jsonb_to_recordset(coalesce(v_snapshot.manifest->'journey_events','[]'::jsonb)) x(event_id uuid,account_id uuid,sh_id uuid) where x.sh_id=v_sh_id and x.account_id=public.current_account_id() and not exists(select 1 from public.journey_events j where j.event_id=x.event_id)),0)+coalesce((select count(*) from jsonb_to_recordset(coalesce(v_snapshot.manifest->'knowledge','[]'::jsonb)) x(knowledge_id uuid,sh_id uuid,scope text) where x.sh_id=v_sh_id and x.scope='PRIVATE' and not exists(select 1 from public.knowledge k where k.knowledge_id=x.knowledge_id)),0)+coalesce((select count(*) from jsonb_to_recordset(coalesce(v_snapshot.manifest->'experiences','[]'::jsonb)) x(experience_id uuid,sh_id uuid,account_id uuid) where x.sh_id=v_sh_id and x.account_id=public.current_account_id() and not exists(select 1 from public.experiences e where e.experience_id=x.experience_id)),0)+coalesce((select count(*) from jsonb_to_recordset(coalesce(v_snapshot.manifest->'legacy_records','[]'::jsonb)) x(legacy_id uuid,source_sh_id uuid) where x.source_sh_id=v_sh_id and not exists(select 1 from public.legacy_records l where l.legacy_id=x.legacy_id)),0) INTO v_missing_after;
  v_missing_after:=v_missing_after+v_attachment_missing_after;
  IF v_missing_after>0 THEN v_continuity_status:='GAP_UNRESOLVED'; v_gap_code:='CONTINUITY_GAP_UNRESOLVED'; ELSE v_continuity_status:='RECOVERED'; v_gap_code:=case when v_missing_before>0 then 'CONTINUITY_GAP_RECOVERED' else null end; END IF;
  INSERT INTO public.recovery_events(snapshot_id,sh_id,outcome,continuity_status,gap_code) VALUES(p_snapshot_id,v_sh_id,'RESTORED',v_continuity_status,v_gap_code) RETURNING recovery_event_id INTO v_recovery_event_id;
  INSERT INTO public.journey_events(sh_id,account_id,event_type,occurred_at,continuity_status,gap_code,payload,source_ref) VALUES(v_sh_id,public.current_account_id(),'RECOVERY',now(),v_continuity_status,v_gap_code,jsonb_build_object('outcome','RESTORED','snapshot_id',p_snapshot_id,'recovery_event_id',v_recovery_event_id,'state_restored',true),'recovery_event:'||v_recovery_event_id::text);
  RETURN v_recovery_event_id;
END;
$$;